export default {
  FIREBASE: 'https://blazing-heat-1438.firebaseio.com/',
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  RECEIVE_CENTER_ITEM: 'RECEIVE_CENTER_ITEM',
  RECEIVE_ITEMS: 'RECEIVE_ITEMS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  VIDEO_IS_READY_TO_PLAY: 'VIDEO_IS_READY_TO_PLAY'
}
