export default {
  FIREBASE: 'https://blazing-heat-1438.firebaseio.com/',
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  PAGE_INITIALLY_SCROLLED_TO_CENTER: 'PAGE_INITIALLY_SCROLLED_TO_CENTER',
  RECEIVE_ITEMS_AND_TIMING: 'RECEIVE_ITEMS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  VIDEO_CHANGED_POSITION: 'VIDEO_CHANGED_POSITION',
  VIDEO_IS_READY_TO_PLAY: 'VIDEO_IS_READY_TO_PLAY',
  WINDOW_CHANGED_SIZE: 'WINDOW_CHANGED_SIZE'
}
