export default {
  FIREBASE: 'https://blazing-heat-1438.firebaseio.com/',
  ITEM_CHANGED_POSITION: 'ITEM_CHANGED_POSITION',
  ITEM_WAS_TOUCHED: 'ITEM_WAS_TOUCHED',
  LOCATION_CHANGED: '@@router/LOCATION_CHANGE',
  PAGE_INITIALLY_SCROLLED_TO_CENTER: 'PAGE_INITIALLY_SCROLLED_TO_CENTER',
  RECEIVED_ASSEMBLY_ID: 'RECEIVED_ASSEMBLY_ID',
  RECEIVED_ITEMS_AND_TIMING: 'RECEIVED_ITEMS',
  RECEIVED_UPLOADS: 'RECEIVED_UPLOADS',
  RECEIVED_USERS: 'RECEIVED_USERS',
  UPLOAD_WAS_CANCELLED: 'UPLOAD_WAS_CANCELLED',
  VIDEO_IS_READY_TO_PLAY: 'VIDEO_IS_READY_TO_PLAY',
  WINDOW_CHANGED_SIZE: 'WINDOW_CHANGED_SIZE'
}
